name: Maestro E2E Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  android_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # --- Android Device Setup & App Installation ---
      - name: Start Android Emulator and Install APK
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 36 # CHANGED: Set to API Level 36 (Android 14)
          target: default
          arch: x86_64
          profile: Pixel_5 # CHANGED: Using a common Pixel profile that mimics a modern device like Pixel 7
          emulator-build: 8000000
          disable-animations: true
          script: |
            echo "Waiting for emulator to be ready..."
            adb wait-for-device shell 'while [ -z "$(getprop sys.boot_completed)" ]; do sleep 1; done;'
            echo "Emulator is ready!"

            APK_PATH="./apps/cloud_app_testing.apk"
            echo "Installing APK: $APK_PATH"
            adb install -r "$APK_PATH"

      # --- Maestro CLI Setup & Test Execution ---
      - name: Install Maestro CLI
        run: |
          curl -Ls "https://get.maestro.mobile.dev" | bash
          echo "$HOME/.maestro/bin" >> $GITHUB_PATH 

      - name: Run Maestro Tests - Android
        run: maestro test ./Android_flows/

      - name: Upload Maestro Test Reports (Android)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: android-maestro-report
          path: maestro-output/report.xml

      - name: Upload Maestro Screenshots (Android)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: android-maestro-screenshots
          path: maestro-output/screenshots

  ios_tests:
    runs-on: macos-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install IDB Companion
        run: |
          brew tap facebook/fb
          brew install facebook/fb/idb-companion

      - name: Start iOS Simulator
        uses: futureware-tech/simulator-action@v2
        with:
          model: 'iPhone 14 Pro'

      - name: Install iOS .app
        run: |
          APP_PATH="./apps/Headlamp Stage.app"
          echo "Installing App: $APP_PATH"
          xcrun simctl install Booted "$APP_PATH"

      - name: Install Maestro CLI
        run: |
          curl -Ls "https://get.maestro.mobile.dev" | bash
          echo "$HOME/.maestro/bin" >> $GITHUB_PATH 

      - name: Run Maestro Tests - iOS
        run: maestro test ./ios_flows/

      - name: Upload Maestro Test Reports (iOS)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ios-maestro-report
          path: maestro-output/report.xml

      - name: Upload Maestro Screenshots (iOS)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ios-maestro-screenshots
          path: maestro-output/screenshots
